### ISSUE TITLE
Create merge pipeline

### ISSUE THREAD

**Issue by joecummings** [isi-vista/cdse-covid#106]
Issue for documenting the process of creating a Pegasus pipeline for merging claim frame information.

### Expected inputs:
- Collection of AIF document pairs, one from ISI and one from UIUC

### Matching process:
- First try by fuzzy matching on spans

### Merge process:
| claim object | process | done |
| ------------| --- | ---- |
| sentence | same between systems | Y |
| span |  | |
| x variable | outer join, followed by confidence score if conflict | |
| claimer | outer join, followed by confidence score if conflict (need to make sure the claimer_debug information is available)  | |
| topic | outer join, followed by confidence score if conflict (will be direct confidence scores from both here) | |
| subtopic | outer join, followed by confidence score if conflict (will be direct confidence scores from both here) | |
| template | outer join, followed by confidence score if conflict (will be direct confidence scores from both here) | |
| claim semantics events | full outer join | |
| claim semantics args | full outer join | | 
| claimer identity qnode | confidence scores (need UIUC to provide these) | | 
| claimer type qnode | currently only provided by ISI | |
| x variable identity qnode | confidence scores (need UIUC to provide these) | |
| x variable type qnode | currently only provided by ISI | |

### Expected output:
- Collection of merged AIF documents

**Comment by danielnapierski** [comment]
Seeing ~2100 claim semantics, each with Entities.  Roughly ~600 also have Events.

**Comment by joecummings** [comment]
Thanks, @danielnapierski , this is ~30% of all claim semantics, which I would consider non-negligible, but ISI's system will greatly augment these events.

**Comment by danielnapierski** [comment]
Python for reading in and writing a graph https://github.com/isi-vista/aida-tools/issues/390
